<?php
/**
 * Route Definitions
 * Maps URL patterns to Controller methods
 */

return [
    // Public Pages
    'GET /' => ['HomeController', 'index'],
    'GET /movie/{id}' => ['MovieController', 'detail'],
    'GET /tv/{id}' => ['TVController', 'detail'],
    'GET /watch/movie/{id}' => ['WatchController', 'movie'],
    'GET /watch/tv/{id}/{season}/{episode}' => ['WatchController', 'tv'],
    'GET /search' => ['SearchController', 'index'],
    'GET /browse/movies' => ['BrowseController', 'movies'],
    'GET /browse/tv' => ['BrowseController', 'tv'],
    'GET /browse/anime' => ['BrowseController', 'anime'],
    'GET /movies/{slug}' => ['HubController', 'movieHub'],
    'GET /tv/trending' => ['HubController', 'tvTrending'],
    'GET /anime/popular' => ['HubController', 'animePopular'],
    'GET /best/{topic}' => ['EditorialController', 'best'],
    'GET /top/{topic}' => ['EditorialController', 'top'],
    'GET /movies-like/{slug}' => ['EditorialController', 'moviesLike'],
    'GET /editorial' => ['EditorialController', 'index'],
    'GET /actors' => ['EntityController', 'actorsIndex'],
    'GET /directors' => ['EntityController', 'directorsIndex'],
    'GET /studios' => ['EntityController', 'studiosIndex'],
    'GET /actor/{slug}' => ['EntityController', 'actorDetail'],
    'GET /director/{slug}' => ['EntityController', 'directorDetail'],
    'GET /studio/{slug}' => ['EntityController', 'studioDetail'],
    'GET /collection/{slug}' => ['EntityController', 'collectionDetail'],
    'GET /collections' => ['CollectionController', 'index'],
    'GET /my-list' => ['StaticController', 'myList'],
    'GET /requests' => ['RequestsController', 'index'],
    'GET /about' => ['TrustPageController', 'about'],
    'GET /contact' => ['TrustPageController', 'contact'],
    'GET /privacy' => ['TrustPageController', 'privacy'],
    'GET /privacy-policy' => ['TrustPageController', 'privacyPolicy'],
    'GET /terms' => ['TrustPageController', 'terms'],
    'GET /dmca' => ['TrustPageController', 'dmca'],
    
    // SEO Routes
    'GET /sitemap.xml' => ['SitemapController', 'index'],
    'GET /sitemap/{slug}.xml' => ['SitemapController', 'subSitemap'],
    'GET /robots.txt' => ['SitemapController', 'robots'],
    'GET /{key}.txt' => ['SitemapController', 'indexNowKey'],
    
    // API Routes (JSON)
    'POST /api/comments' => ['ApiController', 'createComment'],
    'GET /api/comments' => ['ApiController', 'getComments'],
    'GET /api/content-signals' => ['ApiController', 'contentSignals'],
    'POST /api/requests' => ['ApiController', 'createRequest'],
    'GET /api/requests' => ['ApiController', 'getRequests'],
    'PATCH /api/requests' => ['ApiController', 'upvoteRequest'],
    'GET /api/visitors' => ['ApiController', 'trackVisitor'],
    'GET /api/traffics/data' => ['ApiController', 'trafficData'],
    'GET /api/traffics/live' => ['ApiController', 'trafficLive'],
    'GET /api/traffics/stream' => ['ApiController', 'trafficStream'],
    
    // Admin Routes (protected)
    'GET /admin' => ['Admin\\DashboardController', 'index'],
    'GET /admin/login' => ['Admin\\AuthController', 'loginForm'],
    'POST /admin/login' => ['Admin\\AuthController', 'login'],
    'GET /admin/logout' => ['Admin\\AuthController', 'logout'],
    'GET /admin/analytics' => ['Admin\\AnalyticsController', 'index'],
    'GET /admin/analytics/live' => ['Admin\\AnalyticsController', 'live'],
    'GET /admin/comments' => ['Admin\\CommentsController', 'index'],
    'POST /admin/comments/delete' => ['Admin\\CommentsController', 'delete'],
    'POST /admin/comments/bulk-delete' => ['Admin\\CommentsController', 'bulkDelete'],
    'GET /admin/requests' => ['Admin\\RequestsController', 'index'],
    'POST /admin/requests/status' => ['Admin\\RequestsController', 'updateStatus'],
    'POST /admin/requests/delete' => ['Admin\\RequestsController', 'delete'],
    'GET /admin/content' => ['Admin\\ContentController', 'index'],
    'POST /admin/content/collections' => ['Admin\\ContentController', 'updateCollections'],
    'GET /admin/seo' => ['Admin\\SEOController', 'index'],
    'GET /admin/seo/audit' => ['Admin\\SEOController', 'audit'],
    'POST /admin/seo/audit/run' => ['Admin\\SEOController', 'runAudit'],
    'GET /admin/seo/titles' => ['Admin\\SEOController', 'testTitles'],
    'GET /admin/seo/indexnow' => ['Admin\\SEOController', 'triggerIndexNow'],
    'GET /admin/ads' => ['Admin\\AdsController', 'index'],
    'POST /admin/ads/update' => ['Admin\\AdsController', 'update'],
    'GET /admin/cache' => ['Admin\\CacheController', 'index'],
    'POST /admin/cache/clear' => ['Admin\\CacheController', 'clear'],
    'POST /admin/cache/warm' => ['Admin\\CacheController', 'warm'],
    'GET /admin/settings' => ['Admin\\SettingsController', 'index'],
    'POST /admin/settings/update' => ['Admin\\SettingsController', 'update'],
    'GET /admin/users' => ['Admin\\AuthController', 'users'],
    'POST /admin/users/create' => ['Admin\\AuthController', 'createUser'],
];
